= Heading

```asciidoc
= h1
== h2
=== h3
==== h4
===== h5
```

= h1
== h2
=== h3
==== h4
===== h5

= Specising

```asciidoc
{nbsp} +
{sp} +
{empty} +
{zwsp} +
{blank} +
```

{blank} +

= Typography

{blank} +

=== Quoted text

```asciidoc
I can't believe it, we *won*!
```
I can't believe it, we *won*!

{blank} +

=== Bold, italic, and monospace formatting syntax

```asciidoc
bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained
```

bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained



{blank} +

=== Replacements

. Copyright > +++  (C) +++ > (C)
. Registered > +++  (R) +++ > (R)
. Trademark > +++  (TM) +++ > (TM)
. Em dash > +++  -- +++ > --
. Ellipsis > +++  ... +++ > ...
. Single right arrow > +++  -> +++ > ->
. Double right arrow > +++  => +++ > =>
. Single left arrow > +++  <- +++ > <-
. Double left arrow > +++  <= +++ > <=



{blank} +

=== xxxxxxxx

```asciidoc
```


{blank} +

=== xxxxxxxx

```asciidoc
```

{blank} +

=== xxxxxxxx

```asciidoc
```




{empty} +

= Wrapped text and hard line breaks


=== Line breaks preserved using a space followed by the plus sign (+)

```asciidoc
Rubies are red, +
Topazes are blue.
```
Rubies are red, +
Topazes are blue.





=== Line breaks preserved using the hardbreaks option

```asciidoc
[%hardbreaks]
Ruby is red.
Java is black.
```

[%hardbreaks]
Ruby is red.
Java is black.

{empty} +

= List

. Unordered
. Ordered
. Description


=== Lists of things

.1st Way
```asciidoc
* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson
```

* Edgar Allen Poe
* Sheri S. Tepper
* Bill Bryson

{blank} +

.2nd Way
```asciidoc
- Edgar Allen Poe
- Sheri S. Tepper
- Bill Bryson
```

- Edgar Allen Poe
- Sheri S. Tepper
- Bill Bryson

{blank} +

.3rd Way Nested
```asciidoc
* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1
```
* level 1
** level 2
*** level 3
**** level 4
***** level 5
* level 1


=== Ordering the things

.Basic Way
```asciidoc
. Protons
. Electrons
. Neutrons
```
. Protons
. Electrons
. Neutrons

{blank} +

.The step will Started from 4
```asciidoc
[start=4]
. Step four
. Step five
. Step six
```
[start=4]
. Step four
. Step five
. Step six

{blank} +

.Step can be reversed order


```asciidoc
[%reversed]
. Protons
. Electrons
. Neutrons
```

[%reversed]
. Protons
. Electrons
. Neutrons

{blank} +

.A nested ordered list

```asciidoc
. Step 1
. Step 2
.. Step 2a
.. Step 2b
. Step 3
```

. Step 1
. Step 2
.. Step 2a
.. Step 2b
. Step 3

{empty} +

=== Description lists

.1st Way
```asciidoc
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.
```

CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
Keyboard:: Used to enter text or control items on the screen.
Mouse:: Used to point to and select items on your computer screen.
Monitor:: Displays information in visual form using text and graphics.

{blank} +

.Horizontal Way
```asciidoc
[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.
```
[horizontal]
CPU:: The brain of the computer.
Hard drive:: Permanent storage for operating system and/or user files.
RAM:: Temporarily stores information the CPU uses during operation.

{blank} +

.Another Way
```asciidoc
Dairy::
* Milk
* Eggs
Bakery::
* Bread
Produce::
* Bananas
```

Dairy::
* Milk
* Eggs
Bakery::
* Bread
Produce::
* Bananas

{blank} +

=== A hybrid list

```asciidoc
Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace
```

Operating Systems::
  Linux:::
    . Fedora
      * Desktop
    . Ubuntu
      * Desktop
      * Server
  BSD:::
    . FreeBSD
    . NetBSD

Cloud Providers::
  PaaS:::
    . OpenShift
    . CloudBees
  IaaS:::
    . Amazon EC2
    . Rackspace

{empty} +

=== A list with complex content

```
* The header in AsciiDoc must start with a document title.
+
----
= Document Title
----
+
Keep in mind that the header is optional.

* Optional Author and Revision information immediately follows the header title.
+
----
= Document Title
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
----
```

* The header in AsciiDoc must start with a document title.
+
----
= Document Title
----
+
Keep in mind that the header is optional.

* Optional Author and Revision information immediately follows the header title.
+
----
= Document Title
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
----


{blank} +

= Links and images


=== Anatomy of a Link macro

```asciidoc
link:url[optional link text, optional target attribute, optional role attribute]

link:http://www.hmtmcse.com[HMTMCSE]

link:http://www.hmtmcse.com[HMTMCSE in New Window, window=_blank]

```

. link:http://www.hmtmcse.com[HMTMCSE]
. link:http://www.hmtmcse.com[HMTMCSE in New Window, window=_blank]


{blank} +

=== Anatomy of a Images macro

```asciidoc
image::url[optional link text, optional target attribute, optional role attribute]

image::https://avatars2.githubusercontent.com/u/1875791?s=460&v=4[HMTMCSE, 300, 300]
image::https://avatars2.githubusercontent.com/u/1875791?s=460&v=4[HMTMCSE]
image:https://avatars2.githubusercontent.com/u/1875791?s=460&v=4[HMTMCSE, 100, 100, title="Touhid Mia"]
```

image::https://avatars2.githubusercontent.com/u/1875791?s=460&v=4[HMTMCSE, 300, 300]
image::https://avatars2.githubusercontent.com/u/1875791?s=460&v=4[HMTMCSE]
image:https://avatars2.githubusercontent.com/u/1875791?s=460&v=4[HMTMCSE, 100, 100, title="Touhid Mia"]




{blank} +

= Table


=== Example 1

```asciidoc
[cols=2*]
|===
|Firefox
|Web Browser

|Ruby
|Programming Language

|TorqueBox
|Application Server
|===
```
[cols=2*]
|===
|Firefox
|Web Browser

|Ruby
|Programming Language

|TorqueBox
|Application Server
|===


{blank} +

=== Example 2

```asciidoc
[cols=2*,options=header]
|===
|Name
|Group

|Firefox
|Web Browser

|Ruby
|Programming Language
|===
```

[cols=2*,options=header]
|===
|Name
|Group

|Firefox
|Web Browser

|Ruby
|Programming Language
|===


{blank} +

=== Example 3

```asciidoc
|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance, portability.

|Ruby
|Programming Language
|A programmer's best friend.
|===
```

|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance, portability.

|Ruby
|Programming Language
|A programmer's best friend.
|===


{blank} +

=== Example 4
You can set the relative widths of each column using column specifiers—a comma-separated list of relative values defined in the cols block attribute. The number of entries in the list determines the number of columns.
```asciidoc
[cols="2,3,5"]
|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance and portability.

|Ruby
|Programming Language
|A programmer's best friend.
|===
```
[cols="2,3,5"]
|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for standards compliance,
performance and portability.

|Ruby
|Programming Language
|A programmer's best friend.
|===



{blank} +

=== Example 5
If you want to include blocks or lists inside the contents of a column, you can put an a (for AsciiDoc) at the end of the column’s relative value.
```asciidoc
[cols="2,3,5a"]
|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for:

* standards compliance,
* performance and
* portability.

|Ruby
|Programming Language
|A programmer's best friend.
|===
```

[cols="2,3,5a"]
|===
|Name |Group |Description

|Firefox
|Web Browser
|Mozilla Firefox is an open-source web browser.
It's designed for:

* standards compliance,
* performance and
* portability.

|Ruby
|Programming Language
|A programmer's best friend.
|===

[NOTE]
====
Alternatively, you can apply the AsciiDoc style to an individual cell by prefixing the vertical bar with an a:

```asciidoc
a|Mozilla Firefox is an open-source web browser.
It's designed for:

* standards compliance,
* performance and
* portability.
```
====




{blank} +

=== Example 6

```asciidoc
[%header,format=csv]
|===
Artist,Track,Genre
Baauer,Harlem Shake,Hip Hop
The Lumineers,Ho Hey,Folk Rock
|===
```
[%header,format=csv]
|===
Artist,Track,Genre
Baauer,Harlem Shake,Hip Hop
The Lumineers,Ho Hey,Folk Rock
|===

[NOTE]
====
using an include::[] directive:

```asciidoc
[%header,format=csv]
|===
 include::tracks.csv[]
|===
```
====


{blank} +

=== Example 7

```asciidoc
,===
a,b,c
,===

:===
a:b:c
:===

```

,===
a,b,c
,===

:===
a:b:c
:===




{empty} +

= Admonitions

. NOTE
. TIP
. IMPORTANT
. CAUTION
. WARNING

{blank} +

=== NOTE

```asciidoc
WARNING: Wolpertingers are known to nest in server racks.   
Enter at your own risk.
```
WARNING: Wolpertingers are known to nest in server racks.   
Enter at your own risk.


{blank} +

=== TIP

```asciidoc
TIP: This is Example text for describe something.
```
TIP: This is Example text for describe something.

{blank} +

=== IMPORTANT

```asciidoc
IMPORTANT: This is Example text for describe something.
```
IMPORTANT: This is Example text for describe something.


{blank} +

=== CAUTION

```asciidoc
CAUTION: This is Example text for describe something.
```
CAUTION: This is Example text for describe something.


{blank} +

=== WARNING

```asciidoc
WARNING: This is Example text for describe something.
```
WARNING: This is Example text for describe something.



{blank} +

=== xxxxxxxx

```asciidoc
```




{blank} +

.References:
. https://asciidoctor.org/docs/asciidoc-writers-guide/